/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import businesslogic.PermisoAdministradorBL;
import businesslogic.PermisoBL;
import businesslogic.ValidacionBL;
import businesslogic.VersionBL;
import clases.Permiso;
import clases.PermisoAdministrador;
import dataaccess.PermisoDAO;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angelcampos
 */
public class TestForm extends javax.swing.JFrame {

    /**
     * Creates new form TestForm
     */
    public TestForm() {
        initComponents();
        setTitle("Pruebas");
        setResizable(false);
        this.setLocationRelativeTo(null);

        //ObtenerVersion
        if (VersionBL.getInstance().validarVersion() != "0") {
            //Mostrar permisos en un combo
            PermisoBL.getInstance().listarPermiso(comboPermiso);

            //Mostrar permisos en un table
            //mostrarPermisos();
            
            mostrarUsuario();
        } else {
            System.out.println("Actualziar");
            comboPermiso.removeAllItems();
            
            tablePermiso = new JTable(model);
            jScrollPane1.setViewportView(tablePermiso);

            model.addColumn("ID");
            model.addColumn("PERMISO");

            tablePermiso.getColumnModel().getColumn(0).setMaxWidth(0);
            tablePermiso.getColumnModel().getColumn(0).setMinWidth(0);
            tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        }
    }

    /**
     * Declaracion de variable
     */
    int permisoId = 0;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboPermiso = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePermiso = new javax.swing.JTable();
        txt_nombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboPermiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPermisoActionPerformed(evt);
            }
        });

        tablePermiso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePermiso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePermisoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePermiso);

        txt_nombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_nombreInputMethodTextChanged(evt);
            }
        });
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPermisoActionPerformed
        // TODO add your handling code here:
        Permiso permiso = (Permiso) comboPermiso.getSelectedItem();
        try {
            permisoId = permiso.getId();
        } catch (Exception e) {
            permisoId = 0;
        }
        System.out.println(permisoId);
    }//GEN-LAST:event_comboPermisoActionPerformed

    private void tablePermisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePermisoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tablePermisoMouseClicked

    private void txt_nombreInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_nombreInputMethodTextChanged
        // TODO add your handling code here:
        System.out.println("a");
    }//GEN-LAST:event_txt_nombreInputMethodTextChanged

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        // TODO add your handling code here:
        ValidacionBL.getInstance().validarDobleEspacio(txt_nombre.getText(), evt);
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_nombreKeyPressed

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyChar() != KeyEvent.VK_SPACE){
            txt_nombre.setText(ValidacionBL.getInstance().capitalizarCadena(txt_nombre.getText()));
        }
        
    }//GEN-LAST:event_txt_nombreKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboPermiso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePermiso;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que muestra los permisos en un table y agrega los eventos
     * correspondientes
     */
    private void mostrarPermisos() {
        tablePermiso = new JTable(model);
        jScrollPane1.setViewportView(tablePermiso);

        model.addColumn("ID");
        model.addColumn("PERMISO");

        ArrayList<Permiso> permisoList = PermisoDAO.getInstance().getPermiso();
        for (Permiso permiso : permisoList) {
            Object[] fila = new Object[2];
            fila[0] = permiso.getId();
            fila[1] = permiso.getTipo();
            model.addRow(fila);
        }

        tablePermiso.getColumnModel().getColumn(0).setMaxWidth(0);
        tablePermiso.getColumnModel().getColumn(0).setMinWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        tablePermiso.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int indice = tablePermiso.rowAtPoint(e.getPoint());
                if (indice > -1) {
                    System.out.println((String) model.getValueAt(indice, 1));
                }
            }
        });
    }
    
    /**
     * Método que muestra los usuario en un table
     */
    private void mostrarUsuario(){
        tablePermiso = new JTable(model);
        jScrollPane1.setViewportView(tablePermiso);
        
        model.addColumn("PAID");
        model.addColumn("NICK");
        model.addColumn("PASS");
        model.addColumn("ACTIVO");
        model.addColumn("AID");
        model.addColumn("NOMBRE");
        model.addColumn("PID");
        model.addColumn("PERMISO");
        
        ArrayList<PermisoAdministrador> usuarioList = PermisoAdministradorBL.getInstance().listarUsuario(1);
        for (PermisoAdministrador permisoAdministrador : usuarioList) {
            Object[] fila = new Object[8];
            fila[0] = permisoAdministrador.getId();
            fila[1] = permisoAdministrador.getNickname();
            fila[2] = permisoAdministrador.getPass();
            fila[3] = permisoAdministrador.getActivo();
            fila[4] = permisoAdministrador.getAdministrador().getId();
            fila[5] = permisoAdministrador.getAdministrador().getNombre();
            fila[6] = permisoAdministrador.getPermiso().getId();
            fila[7] = permisoAdministrador.getPermiso().getTipo();
            model.addRow(fila);
        }
        
        tablePermiso.getColumnModel().getColumn(0).setMaxWidth(0);
        tablePermiso.getColumnModel().getColumn(0).setMinWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tablePermiso.getColumnModel().getColumn(0).setMaxWidth(1);
        tablePermiso.getColumnModel().getColumn(0).setMinWidth(1);
        tablePermiso.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
        tablePermiso.getColumnModel().getColumn(2).setMaxWidth(0);
        tablePermiso.getColumnModel().getColumn(2).setMinWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
        tablePermiso.getColumnModel().getColumn(3).setMaxWidth(0);
        tablePermiso.getColumnModel().getColumn(3).setMinWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);
        tablePermiso.getColumnModel().getColumn(4).setMaxWidth(0);
        tablePermiso.getColumnModel().getColumn(4).setMinWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(4).setMinWidth(0);
        tablePermiso.getColumnModel().getColumn(6).setMaxWidth(0);
        tablePermiso.getColumnModel().getColumn(6).setMinWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(6).setMinWidth(0);
        
    }
}
