/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import businesslogic.PermisoBL;
import businesslogic.VersionBL;
import clases.Permiso;
import dataaccess.PermisoDAO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angelcampos
 */
public class TestForm extends javax.swing.JFrame {

    /**
     * Creates new form TestForm
     */
    public TestForm() {
        initComponents();
        setTitle("Pruebas");
        setResizable(false);
        this.setLocationRelativeTo(null);

        //ObtenerVersion
        if (VersionBL.getInstance().validarVersion() != "0") {
            //Mostrar permisos en un combo
            PermisoBL.getInstance().listarPermiso(comboPermiso);

            //Mostrar permisos en un table
            mostrarPermisos();
        } else {
            System.out.println("Actualziar");
            comboPermiso.removeAllItems();
            
            tablePermiso = new JTable(model);
            jScrollPane1.setViewportView(tablePermiso);

            model.addColumn("ID");
            model.addColumn("PERMISO");

            tablePermiso.getColumnModel().getColumn(0).setMaxWidth(0);
            tablePermiso.getColumnModel().getColumn(0).setMinWidth(0);
            tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        }
    }

    /**
     * Declaracion de variable
     */
    int permisoId = 0;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboPermiso = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePermiso = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboPermiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPermisoActionPerformed(evt);
            }
        });

        tablePermiso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePermiso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePermisoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePermiso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPermisoActionPerformed
        // TODO add your handling code here:
        Permiso permiso = (Permiso) comboPermiso.getSelectedItem();
        try {
            permisoId = permiso.getId();
        } catch (Exception e) {
            permisoId = 0;
        }
        System.out.println(permisoId);
    }//GEN-LAST:event_comboPermisoActionPerformed

    private void tablePermisoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePermisoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tablePermisoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboPermiso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePermiso;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que muestra los permisos en un table y agrega los eventos
     * correspondientes
     */
    private void mostrarPermisos() {
        tablePermiso = new JTable(model);
        jScrollPane1.setViewportView(tablePermiso);

        model.addColumn("ID");
        model.addColumn("PERMISO");

        ArrayList<Permiso> permisoList = PermisoDAO.getInstance().getPermiso();
        for (Permiso permiso : permisoList) {
            Object[] fila = new Object[2];
            fila[0] = permiso.getId();
            fila[1] = permiso.getTipo();
            model.addRow(fila);
        }

        tablePermiso.getColumnModel().getColumn(0).setMaxWidth(0);
        tablePermiso.getColumnModel().getColumn(0).setMinWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tablePermiso.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        tablePermiso.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int indice = tablePermiso.rowAtPoint(e.getPoint());
                if (indice > -1) {
                    System.out.println((String) model.getValueAt(indice, 1));
                }
            }
        });
    }
}
